org: bachdo
app: aws-serverless-htw
service: aws-serverless-htw
frameworkVersion: '2'

provider:
  name: aws
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
           - "arn:aws:s3:::ibkm-htw-data"
           - "arn:aws:s3:::ibkm-htw-data/*"
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: '20201221'


functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
